### ISSUE TITLE
slate-testing-library: why creating two Editors?

### ISSUE THREAD

**Issue by tzelonm** [ConvertKit/slate-plugins#12]
@brendancarney 
First, I want to thank you on the plugins, it's very helpful to see how others build their slate editor.
I'm interested in the implementation of the testing library. It would be great if you can expend that.

Thank you.

**Comment by brendancarney** [comment]
Hi @tzelonm. Thank you for checking it out! 

First, I'll say that `slate-testing-library` is pretty experimental, as we're still learning the best way to test our slate editors. That being said, we're using it all over and it's working well for us. 

Regarding the two editors: One is created solely for the helper function `createValue`. What this does is allow you to create a slate value that goes through an editor with the exact same plugins as the one you are testing. So, if you have plugins that normalize a value, any value passed to `createValue` will also have those normalizations applied. Does that make sense? 

I'm not 100% sure if this is the best strategy yet, but open to other thoughts or ideas. Thanks again for your question, and let me know if I can clarify anything.
