### ISSUE TITLE
createEvent for space replace key: " " to "Space"

### ISSUE THREAD

**Issue by Tzelon** [ConvertKit/slate-plugins#14]
I found it counter-intuitive to use the " " for space event, what do you think about changing it to "Space"?

**Comment by brendancarney** [comment]
Hi @Tzelon, thanks for the issue! The reason it is " " is because that's what the browser uses. 

I think it may be more confusing to make space the exception.

**Comment by Tzelon** [comment]
Fair enough. 👍
