### ISSUE TITLE
Lists: cannot embed numbered list in unordered list

### ISSUE THREAD

**Issue by wmertens** [ConvertKit/slate-plugins#18]
clicking the numbered list button just cancels the list. I assume the toggle needs to check the list type

**Comment by brendancarney** [comment]
Yes, so the logic should be something like this when toggling a list:

**if not a list:** make it a list with the specified type
**if a list of same type:** unwrap the list
**if a list of different type:** change the list type

**Comment by wmertens** [comment]
Hmm, yes, but changing the list type should only apply to the current level

**Comment by brendancarney** [comment]
Released in `0.2.0`
