### ISSUE TITLE
List item deleted when changing depth

### ISSUE THREAD

**Issue by adjourn** [ConvertKit/slate-plugins#22]
How to reproduce:

* Go to [list docs](https://convertkit-slate-plugins.netlify.com/plugins/slate-lists)
* Drop caret into either `Subitem 2` or `Item 2`
* If `Item 2`, increasing depth deletes the item
* If `Subitem 2`, decrease depth and if then increased, item gets deleted

It also seems that if you repeat `Subitem 2` steps for middle list item in a sub-list that has more than 2 items, all list items after that one get deleted after depth increase. Don't remember seeing this bug before.

Ubuntu, Chromium (can't test it on other platforms at the moment)

**Comment by brendancarney** [comment]
Thanks for the issue @adjourn! I have also confirmed it (OSX Chrome)  and am looking into it.

**Comment by brendancarney** [comment]
Ok, I have a PR (#23) out for it. Let me know if you see any issues. Thanks again!

**Comment by adjourn** [comment]
Looks good but Im unable to test it because I have no idea how to add a package based on pull request with yarn and monorepo. Thanks for the quick PR though.

You might want to consider postpone publishing right after this PR, I've discovered that `Backspace` and `Delete` have very different behaviors (`Delete` is off) and I don't think it's how you meant it to be.

I'll open another issue for that.

**Comment by brendancarney** [comment]
I'll have to look into how you can do that, I'm not sure either. I always have the repo locally so I `yarn link`. For some reason the deploy preview isn't working for this PR either. 

And thanks! I'll look into the other issue when you create it.
