### ISSUE TITLE
slate-lists example

### ISSUE THREAD

**Issue by matt-erhart** [ConvertKit/slate-plugins#29]
Is there complete example around? Maybe codepen?

**Comment by brendancarney** [comment]
There's one example in the docs: https://convertkit-slate-plugins.netlify.com/plugins/slate-lists
Code here: https://github.com/ConvertKit/slate-plugins/blob/master/packages/slate-lists/docs/test-editor.js

But I really like the idea of a live example on something like codepen. I use CodeSandbox, so I'd probably do it there. Let me know if there's something specific you want to see in it.

**Comment by brendancarney** [comment]
Definitely still down for adding more examples, but closing this issue for now.
