### ISSUE TITLE
Paste list item results in an error

### ISSUE THREAD

**Issue by svenadlung** [ConvertKit/slate-plugins#31]
Copy & paste a list item entry results to wrong indentation which leads to an error in schema. See

![Bildschirmfoto 2019-04-30 um 16 06 27](https://user-images.githubusercontent.com/11420688/56967719-108aa700-6b62-11e9-8ba2-f35adf3e3006.png)

**Comment by brendancarney** [comment]
This should be fixed by #54. If not, feel free to reopen. Thanks!
