### ISSUE TITLE
Missing schema normalizations in slate-lists

### ISSUE THREAD

**Issue by alanct-minted** [ConvertKit/slate-plugins#34]
I think there might be some missing normalization rules for `slate-lists`, but haven't had the time to dig into all of it yet. I know at the very least that by highlighting list items and dragging around, I can get my editor into weird states where `list-item-child` blocks don't have child text nodes.

![Screenshot from 2019-05-09 10-05-45](https://user-images.githubusercontent.com/11265352/57464560-8d90dd00-7242-11e9-8f40-76a5e73dd560.png)
![Screenshot from 2019-05-09 10-06-25](https://user-images.githubusercontent.com/11265352/57464576-91246400-7242-11e9-995a-a82f1f7826d6.png)

Not sure what others are missing/leading to three bullets showing on the same line. A little gif tinkering with the documentation example for a couple seconds. The flash to white at the end is actually the page crashing with the exception below.

![Peek 2019-05-09 10-10](https://user-images.githubusercontent.com/11265352/57464804-02641700-7243-11e9-9f19-7f403c4787fc.gif)
![Screenshot from 2019-05-09 10-11-49](https://user-images.githubusercontent.com/11265352/57464809-055f0780-7243-11e9-9365-3b6053d934c7.png)

**Comment by brendancarney** [comment]
This should be fixed by https://github.com/ConvertKit/slate-plugins/pull/54. If not, feel free to reopen. Thanks!
