### ISSUE TITLE
Warning: As of slate@0.47, the `getNodesAtRange` method has been renamed to `getDescendantsAtRange`.

### ISSUE THREAD

**Issue by MatthewHerbst** [ConvertKit/slate-plugins#43]
I'm getting the following warning when using the lists plugin:

```
As of slate@0.47, the `getNodesAtRange` method has been renamed to `getDescendantsAtRange`.
```

I looked at fixing it but it seems doing so would be a breaking change for this library since it would change the Slate version, but I'm unsure.

**Comment by brendancarney** [comment]
Thanks for filing the issue! We have a PR open for this, but I'm going to hold off addressing it until the function is removed. 

https://github.com/ConvertKit/slate-plugins/pull/37

**Comment by MatthewHerbst** [comment]
Thanks for taking a look @brendancarney. One issue with not addressing this now is that when Slate upgrades and removes it, it will break anyone who upgrades Slate before there is a fix here and this is upgraded. If not addressing this now, would you be open to at least setting a `peerDependency` for Slate for this package so people know which versions are supported?
