### ISSUE TITLE
Order list with multilevel numbering

### ISSUE THREAD

**Issue by MarcoamGarcia** [ConvertKit/slate-plugins#50]
Is it possible to change the order list to have multilevel numbering like:

![image](https://user-images.githubusercontent.com/6241366/64975933-0fa3a900-d8a8-11e9-8ff5-1d3ba09d17a7.png)

That would be more user friendly and easy to read.

**Comment by brendancarney** [comment]
Thanks for writing this issue. For now, this plugin is only concerned with rendering the <ul>, <ol>, and <li> tags, and leaves numbering to the browser. You may be able to accomplish what you want to with CSS though. I'm not 100% sure. Check out https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters.
