### ISSUE TITLE
Add example on docs on Activating code blocks

### ISSUE THREAD

**Issue by Gabri3l** [ConvertKit/slate-plugins#6]
Hey @brendancarney thanks for this plugin! I'm fairly new to Slate and I was having a hard time understanding how to enable a block of code. I am having fun with Slate creating useful shortcuts, maybe it could be a good idea to expand the docs to instruct different ways of enabling code blocks when typing. Maybe that will be a simpler example than having a context menu. Once I have something working I might just send a PR your way if that's ok!

I mean after you get around how things come together in Slate it feels pretty straightforward, but an example with actual code wouldn't hurt.

**Comment by brendancarney** [comment]
Thanks for the issue @Gabri3l. I agree, and would love to have examples in the documentation. That was one of the things I struggled with learning Slate also. We're definitely open to a PR if you have one, and I'll try to come up with ideas also. Feel free to reach out to me in the slate-js Slack group if you have any questions. (I'm @brendan there)

**Comment by brendancarney** [comment]
Done in #20
